# Generated by Django 2.2 on 2026-05-07 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='tetx',
            new_name='text',
        ),
    ]
